package com.bip.sys.codediction.po;

/**
 * SysCxzzzd generated by MyEclipse Persistence Tools
 */

public class SysCxzzzd implements java.io.Serializable {

	// Fields

	private Integer id;

	private String zbmc;

	private String jldw;

	private String dm;

	private String remark;

	// Constructors

	/** default constructor */
	public SysCxzzzd() {
	}

	/** minimal constructor */
	public SysCxzzzd(Integer id, String zbmc) {
		this.id = id;
		this.zbmc = zbmc;
	}

	/** full constructor */
	public SysCxzzzd(Integer id, String zbmc, String jldw, String dm, String remark) {
		this.id = id;
		this.zbmc = zbmc;
		this.jldw = jldw;
		this.dm = dm;
		this.remark = remark;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getZbmc() {
		return this.zbmc;
	}

	public void setZbmc(String zbmc) {
		this.zbmc = zbmc;
	}

	public String getJldw() {
		return this.jldw;
	}

	public void setJldw(String jldw) {
		this.jldw = jldw;
	}

	public String getDm() {
		return this.dm;
	}

	public void setDm(String dm) {
		this.dm = dm;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}