package com.bip.sys.codediction.po;

/**
 * SysJnmbzd generated by MyEclipse Persistence Tools
 */

public class SysJnmbzd implements java.io.Serializable {

	// Fields

	private Long id;

	private Long sjtm;

	private String tmmc;

	private String nd;

	private String ls;

	private String hs;

	// Constructors

	/** default constructor */
	public SysJnmbzd() {
	}

	/** minimal constructor */
	public SysJnmbzd(Long id, Long sjtm) {
		this.id = id;
		this.sjtm = sjtm;
	}

	/** full constructor */
	public SysJnmbzd(Long id, Long sjtm, String tmmc, String nd, String ls,
			String hs) {
		this.id = id;
		this.sjtm = sjtm;
		this.tmmc = tmmc;
		this.nd = nd;
		this.ls = ls;
		this.hs = hs;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getSjtm() {
		return this.sjtm;
	}

	public void setSjtm(Long sjtm) {
		this.sjtm = sjtm;
	}

	public String getTmmc() {
		return this.tmmc;
	}

	public void setTmmc(String tmmc) {
		this.tmmc = tmmc;
	}

	public String getNd() {
		return this.nd;
	}

	public void setNd(String nd) {
		this.nd = nd;
	}

	public String getLs() {
		return this.ls;
	}

	public void setLs(String ls) {
		this.ls = ls;
	}

	public String getHs() {
		return this.hs;
	}

	public void setHs(String hs) {
		this.hs = hs;
	}

}