package com.bip.sys.codediction.po;

/**
 * SysQyzbzd generated by MyEclipse Persistence Tools
 */

public class SysQyzbzd implements java.io.Serializable {

	// Fields

	private Long id;

	private String zbbh;

	private String qybh;

	private String nd;

	private String targetunnit;

	private Double targetvalue;

	// Constructors

	/** default constructor */
	public SysQyzbzd() {
	}

	/** minimal constructor */
	public SysQyzbzd(Long id, String zbbh) {
		this.id = id;
		this.zbbh = zbbh;
	}

	/** full constructor */
	public SysQyzbzd(Long id, String zbbh, String qybh, String nd,
			String targetunnit, Double targetvalue) {
		this.id = id;
		this.zbbh = zbbh;
		this.qybh = qybh;
		this.nd = nd;
		this.targetunnit = targetunnit;
		this.targetvalue = targetvalue;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getZbbh() {
		return this.zbbh;
	}

	public void setZbbh(String zbbh) {
		this.zbbh = zbbh;
	}

	public String getQybh() {
		return this.qybh;
	}

	public void setQybh(String qybh) {
		this.qybh = qybh;
	}

	public String getNd() {
		return this.nd;
	}

	public void setNd(String nd) {
		this.nd = nd;
	}

	public String getTargetunnit() {
		return this.targetunnit;
	}

	public void setTargetunnit(String targetunnit) {
		this.targetunnit = targetunnit;
	}

	public Double getTargetvalue() {
		return this.targetvalue;
	}

	public void setTargetvalue(Double targetvalue) {
		this.targetvalue = targetvalue;
	}

}