package com.bip.sys.codediction.po;

/**
 * SysJjzbzd generated by MyEclipse Persistence Tools
 */

public class SysJjzbzd implements java.io.Serializable {

	// Fields

	private Integer id;

	private String zbdm;
	
	private String zbmc;

	private String jldw;

	private String dm;

	private String remark;

	private String zbbh;

	private String dybh;
	
	private String zbtype;
	
	private String zbTypeName;
	
	private String zbsx;
	
	private String zbvalue;
	
	private String select_flag = "";
	// Constructors

	/** default constructor */
	public SysJjzbzd() {
	}

	/** minimal constructor */
	public SysJjzbzd(Integer id, String zbmc) {
		this.id = id;
		this.zbmc = zbmc;
	}

	/** full constructor */
	public SysJjzbzd(Integer id, String zbmc, String jldw, String dm, String remark,String zbbh,String dybh) {
		this.id = id;
		this.zbmc = zbmc;
		this.jldw = jldw;
		this.dm = dm;
		this.remark = remark;
		this.zbbh = zbbh;
		this.dybh = dybh;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getZbmc() {
		return this.zbmc;
	}

	public void setZbmc(String zbmc) {
		this.zbmc = zbmc;
	}

	public String getJldw() {
		return this.jldw;
	}

	public void setJldw(String jldw) {
		this.jldw = jldw;
	}

	public String getDm() {
		return this.dm;
	}

	public void setDm(String dm) {
		this.dm = dm;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getDybh() {
		return dybh;
	}

	public void setDybh(String dybh) {
		this.dybh = dybh;
	}

	public String getZbbh() {
		return zbbh;
	}

	public void setZbbh(String zbbh) {
		this.zbbh = zbbh;
	}

	public String getZbtype() {
		return zbtype;
	}

	public void setZbtype(String zbtype) {
		this.zbtype = zbtype;
	}

	public String getZbTypeName() {
		return zbTypeName;
	}

	public void setZbTypeName(String zbTypeName) {
		this.zbTypeName = zbTypeName;
	}

	public String getSelect_flag() {
		return select_flag;
	}

	public void setSelect_flag(String selectFlag) {
		select_flag = selectFlag;
	}

	public String getZbsx() {
		return zbsx;
	}

	public void setZbsx(String zbsx) {
		this.zbsx = zbsx;
	}

	public String getZbdm() {
		return zbdm;
	}

	public void setZbdm(String zbdm) {
		this.zbdm = zbdm;
	}

	public String getZbvalue() {
		return zbvalue;
	}

	public void setZbvalue(String zbvalue) {
		this.zbvalue = zbvalue;
	}

}