package com.bip.sys.codediction.po;

/**
 * SysNyzd generated by MyEclipse Persistence Tools
 */

public class SysNyzd implements java.io.Serializable {

	// Fields

	private Integer id;

	private String nybh;

	private String nymc;

	private String jldw;

	private String ckzbxs;

	private String sjbh;

	private String xh;

	private String djzbxs;

	private String remark;

	private String sorttype;

	
	private String cnjldw;
	
	private String cnsorttype;
	// Constructors

	/** default constructor */
	public SysNyzd() {
	}

	/** minimal constructor */
	public SysNyzd(Integer id, String nybh) {
		this.id = id;
		this.nybh = nybh;
	}

	/** full constructor */
	public SysNyzd(Integer id, String nybh, String nymc, String jldw,
			String ckzbxs, String sjbh, String xh, String djzbxs,
			String remark, String sorttype) {
		this.id = id;
		this.nybh = nybh;
		this.nymc = nymc;
		this.jldw = jldw;
		this.ckzbxs = ckzbxs;
		this.sjbh = sjbh;
		this.xh = xh;
		this.djzbxs = djzbxs;
		this.remark = remark;
		this.sorttype = sorttype;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNybh() {
		return this.nybh;
	}

	public void setNybh(String nybh) {
		this.nybh = nybh;
	}

	public String getNymc() {
		return this.nymc;
	}

	public void setNymc(String nymc) {
		this.nymc = nymc;
	}

	public String getJldw() {
		return this.jldw;
	}

	public void setJldw(String jldw) {
		this.jldw = jldw;
	}

	public String getCkzbxs() {
		return this.ckzbxs;
	}

	public void setCkzbxs(String ckzbxs) {
		this.ckzbxs = ckzbxs;
	}

	public String getSjbh() {
		return this.sjbh;
	}

	public void setSjbh(String sjbh) {
		this.sjbh = sjbh;
	}

	public String getXh() {
		return this.xh;
	}

	public void setXh(String xh) {
		this.xh = xh;
	}

	public String getDjzbxs() {
		return this.djzbxs;
	}

	public void setDjzbxs(String djzbxs) {
		this.djzbxs = djzbxs;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getSorttype() {
		return this.sorttype;
	}

	public void setSorttype(String sorttype) {
		this.sorttype = sorttype;
	}

	public String getCnjldw() {
		return cnjldw;
	}

	public void setCnjldw(String cnjldw) {
		this.cnjldw = cnjldw;
	}

	public String getCnsorttype() {
		return cnsorttype;
	}

	public void setCnsorttype(String cnsorttype) {
		this.cnsorttype = cnsorttype;
	}

}