package com.bip.sys.codediction.po;

import com.bip.common.util.Tool;



/**
 * SysNhzbzd generated by MyEclipse Persistence Tools
 */

public class SysNhzbzd implements java.io.Serializable {

	// Fields

	private Integer id;

	private String dm;

	private String zbmc;

	private String jldw;

	private String zxdw;

	private String mxdw;

	private String dwzhxs;

	private String hybh;

	private Double tbyjz;

	private String isimportant;

	private String issaving;

	private String discount;

	private String remark;
	
	private String jsgjzx;
	
	
	private String jsgjmx;

	
	private String cnjldw;
	private String cnzxdw;
	private String cnmxdw;
	private String cnisimportant;
	private String cnissaving;
	
	// Constructors

	/** default constructor */
	public SysNhzbzd() {
	}

	/** minimal constructor */
	public SysNhzbzd(Integer id, String dm) {
		this.id = id;
		this.dm = dm;
	}

	/** full constructor */
	public SysNhzbzd(Integer id, String dm, String zbmc, String jldw, String zxdw,
			String mxdw, String dwzhxs, String hybh, Double tbyjz,
			String isimportant, String issaving, String discount, String remark) {
		this.id = id;
		this.dm = dm;
		this.zbmc = zbmc;
		this.jldw = jldw;
		this.zxdw = zxdw;
		this.mxdw = mxdw;
		this.dwzhxs = dwzhxs;
		this.hybh = hybh;
		this.tbyjz = tbyjz;
		this.isimportant = isimportant;
		this.issaving = issaving;
		this.discount = discount;
		this.remark = remark;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDm() {
		return this.dm;
	}

	public void setDm(String dm) {
		this.dm = dm;
	}

	public String getZbmc() {
		return this.zbmc;
	}

	public void setZbmc(String zbmc) {
		this.zbmc = zbmc;
	}

	public String getJldw() {
		
	return Tool.html(this.jldw);
	}
	
	
	

	public void setJldw(String jldw) {
		
		this.jldw = jldw;
	}

	public String getZxdw() {
		return this.zxdw;
	}

	public void setZxdw(String zxdw) {
		this.zxdw = zxdw;
	}

	public String getMxdw() {
		return this.mxdw;
	}

	public void setMxdw(String mxdw) {
		this.mxdw = mxdw;
	}

	public String getDwzhxs() {
		return this.dwzhxs;
	}

	public void setDwzhxs(String dwzhxs) {
		this.dwzhxs = dwzhxs;
	}

	public String getHybh() {
		return this.hybh;
	}

	public void setHybh(String hybh) {
		this.hybh = hybh;
	}

	public Double getTbyjz() {
		return this.tbyjz;
	}

	public void setTbyjz(Double tbyjz) {
		this.tbyjz = tbyjz;
	}

	public String getIsimportant() {
		return this.isimportant;
	}

	public void setIsimportant(String isimportant) {
		this.isimportant = isimportant;
	}

	public String getIssaving() {
		return this.issaving;
	}

	public void setIssaving(String issaving) {
		this.issaving = issaving;
	}

	public String getDiscount() {
		return this.discount;
	}

	public void setDiscount(String discount) {
		this.discount = discount;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getJsgjmx() {
		return jsgjmx;
	}

	public void setJsgjmx(String jsgjmx) {
		this.jsgjmx = jsgjmx;
	}

	public String getJsgjzx() {
		return jsgjzx;
	}

	public void setJsgjzx(String jsgjzx) {
		this.jsgjzx = jsgjzx;
	}

	public String getCnisimportant() {
		return cnisimportant;
	}

	public void setCnisimportant(String cnisimportant) {
		this.cnisimportant = cnisimportant;
	}

	public String getCnissaving() {
		return cnissaving;
	}

	public void setCnissaving(String cnissaving) {
		this.cnissaving = cnissaving;
	}

	public String getCnjldw() {
		return cnjldw;
	}

	public void setCnjldw(String cnjldw) {
		this.cnjldw = cnjldw;
	}

	public String getCnzxdw() {
		return cnzxdw;
	}

	public void setCnzxdw(String cnzxdw) {
		this.cnzxdw = cnzxdw;
	}

	public String getCnmxdw() {
		return cnmxdw;
	}

	public void setCnmxdw(String cnmxdw) {
		this.cnmxdw = cnmxdw;
	}

}