package com.bip.sys.codediction.po;

/**
 * SysQyqszd generated by MyEclipse Persistence Tools
 */

public class SysQyqszd implements java.io.Serializable {

	// Fields

	private Long id;

	private String zbbh;

	private String qybh;

	private String nd;

	private String tbzjmb;

	private Double zbmbz;

	// Constructors

	/** default constructor */
	public SysQyqszd() {
	}

	/** minimal constructor */
	public SysQyqszd(Long id, String zbbh) {
		this.id = id;
		this.zbbh = zbbh;
	}

	/** full constructor */
	public SysQyqszd(Long id, String zbbh, String qybh, String nd,
			String tbzjmb, Double zbmbz) {
		this.id = id;
		this.zbbh = zbbh;
		this.qybh = qybh;
		this.nd = nd;
		this.tbzjmb = tbzjmb;
		this.zbmbz = zbmbz;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getZbbh() {
		return this.zbbh;
	}

	public void setZbbh(String zbbh) {
		this.zbbh = zbbh;
	}

	public String getQybh() {
		return this.qybh;
	}

	public void setQybh(String qybh) {
		this.qybh = qybh;
	}

	public String getNd() {
		return this.nd;
	}

	public void setNd(String nd) {
		this.nd = nd;
	}

	public String getTbzjmb() {
		return this.tbzjmb;
	}

	public void setTbzjmb(String tbzjmb) {
		this.tbzjmb = tbzjmb;
	}

	public Double getZbmbz() {
		return this.zbmbz;
	}

	public void setZbmbz(Double zbmbz) {
		this.zbmbz = zbmbz;
	}

}