package com.bip.sys.codediction.po;

/**
 * SysSbzd generated by MyEclipse Persistence Tools
 */

public class SysSbzd implements java.io.Serializable {

	// Fields

	private Integer id;
	
	
	private String sbbh;

	private String sblb;

	private String sbmc;

	private String sfttsb;
	
	
	private String cnsfttsb;
	private String cnsblb;

	// Constructors

	/** default constructor */
	public SysSbzd() {
	}

	/** minimal constructor */
	public SysSbzd(Integer id, String sblb) {
		this.id = id;
		this.sblb = sblb;
	}

	/** full constructor */
	public SysSbzd(Integer id, String sblb, String sbmc, String sfttsb) {
		this.id = id;
		this.sblb = sblb;
		this.sbmc = sbmc;
		this.sfttsb = sfttsb;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSblb() {
		return this.sblb;
	}

	public void setSblb(String sblb) {
		this.sblb = sblb;
	}

	public String getSbmc() {
		return this.sbmc;
	}

	public void setSbmc(String sbmc) {
		this.sbmc = sbmc;
	}

	public String getSfttsb() {
		return this.sfttsb;
	}

	public void setSfttsb(String sfttsb) {
		this.sfttsb = sfttsb;
	}

	public String getSbbh() {
		return sbbh;
	}

	public void setSbbh(String sbbh) {
		this.sbbh = sbbh;
	}

	public String getCnsfttsb() {
		return cnsfttsb;
	}

	public void setCnsfttsb(String cnsfttsb) {
		this.cnsfttsb = cnsfttsb;
	}

	public String getCnsblb() {
		return cnsblb;
	}

	public void setCnsblb(String cnsblb) {
		this.cnsblb = cnsblb;
	}

}